jwt:
  # JWT存储的请求体
  tokenHeader: Authorization
  # 加解密使用的密钥
  secret: algebra-secret
  # 超期限时间
  expiration: 604800
  # 负载中拿到开头
  tokenHead: Bearer
spring:
  datasource:
    url: jdbc:mysql://121.41.201.3:3306/algebra?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: amazing-feather
    password: '!Aa12345'
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.feather.algebraback.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000 # 时间高于此毫秒为慢查询
          logSlowSql: true  # 日志是否记录慢sql
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false # 不允许删表

  redis:
    host: 127.0.0.1
    port: 6379

# yztoarbqxupqjebb
  mail:
    host: smtp.qq.com
    username: 1467965694@qq.com
    password: qyahqizklnsqgccc
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081